### ISSUE TITLE
incorrect junit xml for output of xcode 8

### ISSUE THREAD

**Issue by zhanglin-zhou** [supermarin/xcpretty#234] opened 2016-08-17 10:43 UTC
I tried the latest xcpretty from github, found it generate incorrect junit xml. The xcode build log has been uploaded, you can get the out put like:

cat 
[xcodebuild.txt](https://github.com/supermarin/xcpretty/files/422367/xcodebuild.txt)
xcodebuild.txt  | ./xcpretty -r junit
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin15/rbconfig.rb:213: warning: Insecure world writable dir /build in PATH, mode 040777
Selected tests
Test Suite viewUITests.xctest started
vmtAboutWindow

	 Executed 1 test, with 1 failure (0 unexpected) in 22.490 (22.511) seconds

~/git/xcpretty/bin$ more build/reports/junit.xml 
<?xml version='1.0' encoding

='UTF-8'?>
<testsuites name='viewUITests.xctest' tests='0' failures='0'/>

**Comment by johnbill** [comment] 2016-08-29 23:27
+1

**Comment by oozbekta** [comment] 2016-09-07 21:37
+1

**Comment by oozbekta** [comment] 2016-09-08 15:29
It seems like the junit output can capture the successful tests, but not the failed ones.

**Comment by oozbekta** [comment] 2016-09-08 16:29
This is duplicate of #209

**Closed** 2016-09-28 06:10 UTC
