### ISSUE TITLE
xcpretty sometimes ignores test failures when tests crash

### ISSUE THREAD

**Issue by russbishop** [supermarin/xcpretty#209] opened 2016-02-18 07:17 UTC
If a test crashes, xcodebuild will restart the simulator and skip the crashing test. Sometimes this causes xcpretty to ignore the test failures.

It appears to be caused by simultaneous log streams being written. I don't know if that's an artifact of our CI system (Bitrise), xcpretty, or xcodebuild doing something strange.

I'll see things like this in the raw log output:

```
Test Case '-[PlanGridUnitTests.StoreTests testObserved]' started.
Test Case '-[PlaFailing tests:
	-[ReportLogStoreTests testHydratedStateData()]
** TEST FAILED **

nGridUnitTests.StoreTests testObserved]' passed (0.001 seconds).
```

Notice the extra `n` on that last line and the mangled `Test Case '-[PlaFailing` ... 
Clearly the test that `abort`ed and caused a restart emits its failure in the middle of another test case. I've seen even worse examples of mangled output however I've never seen it fail to emit `** TEST FAILED **`. 

Maybe xcpretty should have a fallback in the parsing. If it encounters `** TEST FAILED **` but never saw the actual failure it can at least emit a general failure message to let everyone know things went off the rails.

**Comment by kwoylie** [comment] 2016-02-24 04:53
Hi, I'm also having the exact same problem.

Cheers,

Kylie

**Comment by MatejBalantic** [comment] 2016-04-11 13:01
Seing the same problem in our project

**Comment by nacuteodor** [comment] 2016-05-23 16:50
I 've written a tool that parse the TestSummaries plist file from Logs/Test folder and generates the JUnit report xml file: (https://github.com/nacuteodor/ProcessTestSummaries)
You shouldn't have this problem with that tool. 
Hope that will help you.

**Comment by oozbekta** [comment] 2016-09-08 16:28
Investigating the problem little bit more, I figured out XCode 8 beta 6 no longer outputs:

/PATH_TO_TEST_FILE:LINE: error: -[TARGET.CLASS TEST_METHOD] : timed out waiting for element predicate hasKeyboardFocus == 1

where xcpretty uses a regex for this:
    FAILING_TEST_MATCHER = /^\s*(.+:\d+):\serror:\s[\+\-]\[(.*)\s(.*)\]\s:(?:\s'.*'\s\[FAILED\],)?\s(.*)/

So unfortunately, the issue is not on xcpretty's side. Looks like parsing the TestSummaries file is the solution in this case. thanks @nacuteodor

**Comment by JaNd3r** [comment] 2016-09-14 07:09
I have posted two log file snippets in #236, the second being produced with Xcode 8 beta 6. A failing test is still reported in the log, so xcpretty could eventually fix this by adjusting the matcher (if this is the final Xcode log output format).

    12:52:25.391 Xcode[4390:42228] _XCT_testCaseDidFinishForTestClass:DemoUITests.STORY_13_DemoBilder method:Demobilder_werden_angezeigt withStatus:failed duration:23.86212801933289

A passing test is logged with `withStatus:passed`, a failing test with `withStatus:failed`.

**Comment by ashgti** [comment] 2016-09-14 17:54
I've posted a pull request that is working with Xcode 8 parsing XCUITests, see pull request #240

**Comment by supermarin** [comment] 2016-09-28 06:11
merged, thanks @ashgti !

**Closed by supermarin** 2016-09-28 06:11 UTC

**Comment by manishmittal79** [comment] 2016-10-06 14:43
@supermarin : I am using xcodebuild and xcpretty (with -r junit ) to pipe the output to junit.xml. I have 2 problems using xcpretty currently.

1. My jenkins ci settings are same as recommended, but i am getting empty Emails after test runs. 

My jenkins settings for publish Junit report is "**/junit.xml". I created an empty junit.xml in workspace.

2. Sometime tests are not completely running due to below:
/Users/macuser/.rvm/gems/ruby-2.1.0/gems/xcpretty-0.2.3/lib/xcpretty/reporters/junit.rb:56:in `format_failing_test': undefined method `sub' for nil:NilClass (NoMethodError)
	from /Users/macuser/.rvm/gems/ruby-2.1.0/gems/xcpretty-0.2.3/lib/xcpretty/parser.rb:359:in `parse'
	from /Users/macuser/.rvm/gems/ruby-2.1.0/gems/xcpretty-0.2.3/lib/xcpretty/reporters/junit.rb:27:in `handle'
	from /Users/macuser/.rvm/gems/ruby-2.1.0/gems/xcpretty-0.2.3/bin/xcpretty:85:in `block (2 levels) in <top (required)>'
	from /Users/macuser/.rvm/gems/ruby-2.1.0/gems/xcpretty-0.2.3/bin/xcpretty:85:in `each'
	from /Users/macuser/.rvm/gems/ruby-2.1.0/gems/xcpretty-0.2.3/bin/xcpretty:85:in `block in <top (required)>'
	from /Users/macuser/.rvm/gems/ruby-2.1.0/gems/xcpretty-0.2.3/bin/xcpretty:83:in `each_line'
	from /Users/macuser/.rvm/gems/ruby-2.1.0/gems/xcpretty-0.2.3/bin/xcpretty:83:in `<top (required)>'
	from /Users/macuser/.rvm/gems/ruby-2.1.0/bin/xcpretty:23:in `load'
	from /Users/macuser/.rvm/gems/ruby-2.1.0/bin/xcpretty:23:in `<main>'
	from /Users/macuser/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/macuser/.rvm/gems/ruby-2.1.0/bin/ruby_executable_hooks:15:in `<main>'

Please provide your thoughts on this.
Thanks in advance.
Regards
Manish
