### ISSUE TITLE
Test report does not contain failed tests any more (Xcode 8)

### ISSUE THREAD

**Issue by JaNd3r** [supermarin/xcpretty#236] opened 2016-09-05 08:06 UTC
The test report (.html, .junit) does not show failed UI tests any more. Failed tests are not even counted against the total number of tests executed, so depending on your test suite's size, the report suggests, that all tests were executed successfully although some of them failed.

The report worked with Xcode 8 beta 1 (8S128d), currently I'm using Xcode 8 beta 6 (8S201h) with xcpretty 0.2.2.

I noticed some differences when comparing the raw log files written by Xcode, so it seems, that Apple changed their log output format slightly.

Output with Xcode 8 beta 1:
```
    t =    23.92s         Find: Element at index 0
    t =    23.93s     Assertion Failure: DemoUITests.swift:109: XCTAssertTrue failed - Anzahl der Demo-Bilder (1) stimmt nicht mit der erwarteten Anzahl (4) ueberein.
12:39:37.610 XCTRunner[582:41190] -[_XCTestDriverTestObserver testCase:didFailWithDescription:inFile:atLine:]
12:41:50.455 Xcode[3565:35450] _XCT_testCaseDidFailForTestClass:DemoUITests.STORY_13_DemoBilder method:Demobilder_werden_angezeigt withMessage:XCTAssertTrue failed - Anzahl der Demo-Bilder (1) stimmt nicht mit der erwarteten Anzahl (4) ueberein. file:/Users/cislave/Desktop/Demo_iOS10/DemoApp/DemoUITests/DemoUITests.swift line:109
12:39:37.617 XCTRunner[582:41200] Monitor: termination is being tracked for <XCUIApplicationProcess: 0x1704adce0 com.foo.ios.Demo (591)>
12:39:37.617 XCTRunner[582:41190] Monitor: waiting for state changes to launched application(s): <XCUIApplicationProcess: 0x1704adce0 com.foo.ios.Demo (591)>
12:39:37.820 XCTRunner[582:41190] Monitor: done waiting for state changes to launched application(s)
12:39:37.821 XCTRunner[582:41190] -[STORY_13_DemoBilder Demobilder_werden_angezeigt] started activity <XCActivityRecord: 0x1704ac4e0> 2016-08-31 10:39:37 +0000: Tear Down
12:39:37.825 XCTRunner[582:41190] -[STORY_13_DemoBilder Demobilder_werden_angezeigt] finished activity <XCActivityRecord: 0x1704ac4e0> 2016-08-31 10:39:37 +0000: Tear Down (0.003667s)
    t =    24.14s     Tear Down
Test Case '-[DemoUITests.STORY_13_DemoBilder Demobilder_werden_angezeigt]' failed (24.152 seconds).
12:39:37.829 XCTRunner[582:41190] -[_XCTestDriverTestObserver testCaseDidFinish:]
12:41:50.675 Xcode[3565:35450] _XCT_testCaseDidFinishForTestClass:DemoUITests.STORY_13_DemoBilder method:Demobilder_werden_angezeigt withStatus:failed duration:24.15195995569229
12:41:51.031 Xcode[3565:36014] (LOG ARBITER) Rotating message buffer with 17 messages.
```

Output with Xcode 8 beta 6:
```
    t =    23.63s         Find: Element at index 0
    t =    23.64s     Assertion Failure: DemoUITests.swift:109: XCTAssertTrue failed - Anzahl der Demo-Bilder (1) stimmt nicht mit der erwarteten Anzahl (4) ueberein.
12:50:12.574 testmanagerd[630:45050] -[XCTestManager allowUITestControlForPID:] 635 vs 635
12:50:12.575 testmanagerd[630:45050] Getting screenshot
12:50:12.565 XCTRunner[635:44789] <XCTestExpectationWaiter: 0x17001d1e0>: primitiveWait woke from run loop
12:50:12.566 XCTRunner[635:44789] <XCTestExpectationWaiter: 0x17001d1e0> done waiting
12:50:12.566 XCTRunner[635:44789] <XCTestExpectationWaiter: 0x17001d1e0> cleaning up Expect change to state of <XCUIApplicationProcess: 0x1704af060 com.foo.ios.Demo (646)>
12:50:12.567 XCTRunner[635:44789] Monitor: done waiting for state changes to launched application(s)
12:50:12.567 XCTRunner[635:44789] -[_XCTestDriverTestObserver testCaseDidFinish:]
12:52:25.391 Xcode[4390:42228] _XCT_testCaseDidFinishForTestClass:DemoUITests.STORY_13_DemoBilder method:Demobilder_werden_angezeigt withStatus:failed duration:23.86212801933289
12:52:27.746 Xcode[4390:42796] (LOG ARBITER) Rotating message buffer with 105 messages.
```

**Comment by taylesworth** [comment] 2016-09-13 19:35
Yeah, I'm seeing this with the released Xcode 8 as well.

**Comment by taylesworth** [comment] 2016-09-13 19:44
This is a duplicate of #209 and #234

**Comment by wendywenwen** [comment] 2016-09-19 03:56
I Got the same problem,  the test report doesn't contain the fail test case results in Xcode8!

**Comment by supermarin** [comment] 2016-09-24 10:38
duplicate - will be fixed soon

**Closed by supermarin** 2016-09-24 10:38 UTC
